insert into user values(1, sysdate(), 'bruce.dickinson', 'bruce.dickinson', 'bruce.dickinson');
insert into user values(2, sysdate(), 'slash', 'slash', 'slash');
insert into user values(3, sysdate(), 'flea', 'flea', 'flea');
insert into user values(4, sysdate(), 'antony', 'antony', 'antony');
insert into post values(1000, 'this is a bruce post', 2);
insert into post values(1001, 'this is a bruce post', 2);
insert into post values(1002, 'this is a bruce post', 2);
insert into post values(1003, 'this is a bruce post', 2);
insert into post values(1004, 'this is a flea post', 3);
insert into post values(1005, 'this is a flea post', 3);
insert into post values(1006, 'this is a antony post', 4);
insert into post values(1007, 'this is a antony post', 4);